dist: trusty
sudo: required
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - COMPILER=g++-5

before_install:
  - sudo apt-get install -y libasound-dev
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-src.zip -O premake.zip
  - unzip premake.zip
  - cd premake-5.0.0-alpha12/build/gmake.unix
  - make config=release
  - cd ../../..
  - mv premake-5.0.0-alpha12/bin/release/premake5 premake5
  - pwd
  - ls -la

before_script:
 - pwd
 - ls -la
 - ./premake5 gmake
 - export CXX=$COMPILER
 - $CXX --version

script:
 - make -C build/gmake config=release
 - bin/gmake/release/chirp_tests
