image: Visual Studio 2017

install:
  - ps: Start-FileDownload 'https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-windows.zip' 'premake.zip'
  - 7z x premake.zip
  - premake5.exe vs2017

configuration:
  - Debug
  - Release

test_script:
  - bin\vs2017\%CONFIGURATION%\chirp_tests.exe